let daggerfall_towns = [
    "Abibon-Gora";
    "Agajnu";
    "Agakawan";
    "Agallareg";
    "Agandaweyn";
    "Agazar";
    "Ageliret";
    "Agenanu";
    "Agerabi";
    "Agerana";
    "Agewan";
    "Agibunu";
    "Agiribi";
    "Agissija";
    "Agjiton";
    "Agoccoga";
    "Agogurana";
    "Agotudata";
    "Aguhzar";
    "Aguja";
    "Agunnudai";
    "Agunnuton";
    "Agurea";
    "Aguthulah";
    "Akhaaqbi";
    "Akhabu";
    "Akhahadisu";
    "Akhahanu";
    "Akha-Hassi";
    "Akhakadisu";
    "Akhallaton";
    "Akhascu-Ij";
    "Akhemirea";
    "Akhenator";
    "Akhera-Korom";
    "Akhidai";
    "Akhiirea";
    "Akhilah";
    "Akhoaisa";
    "Akhoguno";
    "Akhoniweyn";
    "Akhoton";
    "Akhotudata";
    "Akhuhzar";
    "Akhulah";
    "Akhuthu-Gora";
    "Akhyrybu";
    "Alcaire";
    "Aldborne";
    "Aldbridge";
    "Aldbrone";
    "Aldbrugh";
    "Aldbury";
    "Aldcart";
    "Aldcastle";
    "Aldcester";
    "Alddale";
    "Aldford";
    "Aldfort";
    "Aldfort Hill";
    "Aldgate";
    "Aldham";
    "Aldhead";
    "Aldhead Rock";
    "Aldhope";
    "Aldingbeth";
    "Aldingborne";
    "Aldingborne Commons";
    "Aldingbridge";
    "Aldingbridge Moor";
    "Aldingbrone";
    "Aldingbury";
    "Aldingcart";
    "Aldingcastle";
    "Aldingcester";
    "Aldingcester Moor";
    "Aldingcroft";
    "Aldingdale";
    "Aldingford";
    "Aldingfort";
    "Aldinggate";
    "Aldingham";
    "Aldinghead";
    "Aldinghope";
    "Aldinghope Garden";
    "Aldingidge";
    "Aldinging";
    "Aldinglech";
    "Aldingleigh";
    "Aldingley";
    "Aldingmarket";
    "Aldingmarket Field";
    "Aldingmont";
    "Aldingmore";
    "Aldingmoth";
    "Aldingmoth Wood";
    "Aldingpath";
    "Aldingshire";
    "Aldingtale";
    "Aldington";
    "Aldingtown";
    "Aldingtry";
    "Aldingvale";
    "Aldingville";
    "Aldingwall";
    "Aldingwark";
    "Aldingwark Wood";
    "Aldingway";
    "Aldingwell";
    "Aldingwich";
    "Aldingwick";
    "Aldingwick Hill";
    "Aldingwood";
    "Aldingwood Garden";
    "Aldingworth";
    "Aldingwych Court";
    "Aldlech";
    "Aldleigh";
    "Aldley";
    "Aldmarket";
    "Aldmont";
    "Aldmore";
    "Aldmoth";
    "Aldpath";
    "Aldpath Hall";
    "Aldshire";
    "Aldton";
    "Aldtower Hill";
    "Aldtry";
    "Aldvale";
    "Aldville";
    "Aldville Borough";
    "Aldwall";
    "Aldwall Rock";
    "Aldwark";
    "Aldway";
    "Aldwell";
    "Aldwich";
    "Aldwick";
    "Aldwold";
    "Aldwood";
    "Aldworth";
    "Aldwych";
    "Aleth";
    "Alik'ra";
    "Antelaaqara";
    "Antelajda";
    "Antelajer";
    "Antelanis";
    "Antelastaza";
    "Antelehret";
    "Antelela";
    "Anteleliisa";
    "Anteleminu";
    "Antelenadai";
    "Anteleralah";
    "Antelettuisa";
    "Antelibuton";
    "Anteliiga";
    "Antelilabia";
    "Antelilliga";
    "Antelino";
    "Antelinrana";
    "Antelirea";
    "Antelissiwan";
    "Anteljinis";
    "Antelohaza";
    "Antelopada";
    "Anteluthusia";
    "Anticlere";
    "Antyphyllos";
    "Appaaqnis";
    "Appadai";
    "Appallarea";
    "Apparana";
    "Appascu-Thar";
    "Appehla";
    "Apperano";
    "Appettudata";
    "Appiiweyn";
    "Appilaja";
    "Appirino";
    "Appissiza";
    "Appoccorea";
    "Appoguza";
    "Appohazar";
    "Appola";
    "Apponiwan";
    "Appuda";
    "Appuga";
    "Appumbator";
    "Appunnusia";
    "Apputhuga";
    "Apputhuwan";
    "Arkbeth";
    "Arkbeth Garden";
    "Arkborne";
    "Arkbridge";
    "Arkbridge Wood";
    "Arkbrone Heath";
    "Arkbrugh";
    "Arkbury";
    "Arkcart";
    "Arkcastle";
    "Arkcester";
    "Arkcroft";
    "Arkdale";
    "Arkford";
    "Arkfort";
    "Arkham";
    "Arkham Hamlet";
    "Arkhead";
    "Arkhope";
    "Arkhope Minster";
    "Arking";
    "Arking Hall";
    "Arklech";
    "Arkley";
    "Arkmarket";
    "Arkmont";
    "Arkmore";
    "Arkmore Minster";
    "Arkmoth";
    "Arkmoth Borough";
    "Arkmoth End";
    "Arkpath";
    "Arkridge";
    "Arkshire";
    "Arktale";
    "Arkton";
    "Arktown";
    "Arktry";
    "Arkville";
    "Arkwall";
    "Arkwark";
    "Arkway";
    "Arkwell";
    "Arkwich";
    "Arkwick";
    "Arkwold";
    "Arkwold Court";
    "Arkwood";
    "Arkwych";
    "Ashing's Guard";
    "Atraaqza";
    "Atradrana";
    "Atrahaga";
    "Atrandarea";
    "Atraza";
    "Atreja";
    "Atrenano";
    "Atretturana";
    "Atriga";
    "Atrilawan";
    "Atrji-Ij";
    "Atroasia";
    "Atroccodisu";
    "Atrohala";
    "Atroni-Gora";
    "Atruhda";
    "Atruhisa";
    "Atrula";
    "Atrumbada";
    "Atruza";
    "Ayasofya";
    "Badai";
    "Baelbeth";
    "Baelborne";
    "Baelborne Field";
    "Baelbridge";
    "Baelbridge Borough";
    "Baelbrone";
    "Baelbrugh";
    "Baelbury";
    "Baelcart";
    "Baelcastle";
    "Baelcester";
    "Baelcroft";
    "Baelcroft Heath";
    "Baeldale";
    "Baelford";
    "Baelgate";
    "Baelham";
    "Baelhead";
    "Baelhead Court";
    "Baelidge";
    "Baellech";
    "Baelleigh";
    "Baelley";
    "Baelmarket";
    "Baelmarket Moor";
    "Baelmont";
    "Baelmore";
    "Baelmoth";
    "Baelshire";
    "Baelshire Wood";
    "Baeltale";
    "Baelton";
    "Baelton Rock";
    "Baeltower";
    "Baeltry";
    "Baelvale";
    "Baelville";
    "Baelwall";
    "Baelwark";
    "Baelwark Commons";
    "Baelway";
    "Baelwell";
    "Baelwich";
    "Baelwick";
    "Baelwold";
    "Baelwood";
    "Baelworth";
    "Baelworth Hamlet";
    "Baelwych";
    "Baghada";
    "Baghad-Thar";
    "Baghahator";
    "Baghajweyn";
    "Baghakaga";
    "Baghakawan";
    "Baghandadisu";
    "Baghascuwan";
    "Baghastarana";
    "Baghenaria";
    "Bagheradax";
    "Baghi-Ij";
    "Baghiitor";
    "Baghila";
    "Baghillidisu";
    "Baghin-Hassi";
    "Baghiri-Thar";
    "Baghissibu";
    "Baghjiwan";
    "Bagho-Gora";
    "Baghopadai";
    "Baghurana";
    "Baghyrynia";
    "Bahazar";
    "Balah";
    "Behla";
    "Bemitor";
    "Beno";
    "Beraja";
    "Berarea";
    "Berbaaqnia";
    "Berbaharia";
    "Berbajan";
    "Berbandaa";
    "Berbascunia";
    "Berbastadax";
    "Berbean";
    "Berbehus";
    "Berbelijet";
    "Berbemijet";
    "Berbenaisa";
    "Berberaplex";
    "Berbettukat";
    "Berbibujet";
    "Berbibusa";
    "Berbilania";
    "Berbillia";
    "Berbinbia";
    "Berbisia";
    "Berbissi-Thar";
    "Berbius";
    "Berbodax";
    "Berbopa-Kom";
    "Bergama";
    "Beton";
    "Betony";
    "Bhoriane";
    "Bibu";
    "Bibudisu";
    "Biilah";
    "Bi-Korom";
    "Binno";
    "Birizar";
    "Blackbeth";
    "Blackbridge";
    "Blackbrone Hill";
    "Blackbrone Moor";
    "Blackbrugh";
    "Blackbrugh Field";
    "Blackbury";
    "Blackbury Hamlet";
    "Blackcart";
    "Blackcart Hollow";
    "Blackcastle";
    "Blackcester";
    "Blackcroft";
    "Blackdale";
    "Blackford";
    "Blackfort";
    "Blackgate";
    "Blackham";
    "Blackhead";
    "Blackhope";
    "Blackidge";
    "Blackidge Hamlet";
    "Blacking";
    "Blacklech";
    "Blackleigh";
    "Blackley";
    "Blackley Commons";
    "Blackmarket";
    "Blackmont";
    "Blackmore";
    "Blackmoth";
    "Blackpath";
    "Blackshire";
    "Blacktale";
    "Blackton";
    "Blacktower";
    "Blacktown";
    "Blacktry";
    "Blackvale";
    "Blackville";
    "Blackwall";
    "Blackwark";
    "Blackway Wood";
    "Blackwell";
    "Blackwich";
    "Blackwich Heath";
    "Blackwick";
    "Blackwold";
    "Blackworth";
    "Blackwych";
    "Boadai";
    "Bobi";
    "Bogudata";
    "Bohabu";
    "Bohaweyn";
    "Bonidisu";
    "Boweyn";
    "Broadbridge";
    "Broadbrone";
    "Broadbrugh";
    "Broadbury";
    "Broadcart";
    "Broadcastle";
    "Broadcester";
    "Broadcroft";
    "Broaddale";
    "Broadford";
    "Broadfort";
    "Broadgate";
    "Broadham";
    "Broadhead";
    "Broadhope";
    "Broadidge";
    "Broading";
    "Broadlech";
    "Broadmarket";
    "Broadmont Heath";
    "Broadmont Wood";
    "Broadmore";
    "Broadpath";
    "Broadpath Minster";
    "Broadshire";
    "Broadshire Hall";
    "Broadtale";
    "Broadtale Wood";
    "Broadton";
    "Broadtower";
    "Broadtown";
    "Broadtry";
    "Broadvale";
    "Broadvale Court";
    "Broadville";
    "Broadville Wood";
    "Broadwall";
    "Broadwark";
    "Broadway";
    "Broadwell";
    "Broadwich Hill";
    "Broadwich Minster";
    "Broadwick";
    "Broadwold";
    "Broadwood";
    "Broadwych";
    "Broaeth";
    "Broaorne";
    "Broarugh Heath";
    "Bubaaqja";
    "Bubadja";
    "Bubandanis";
    "Bubastajer";
    "Bubehda";
    "Bubemia";
    "Bubibureg";
    "Bubiinu";
    "Bubilliga";
    "Bubissidata";
    "Bubiton";
    "Bubjinis";
    "Buboaan";
    "Bubobia";
    "Bubogureg";
    "Bubohabia";
    "Bubohaisa";
    "Bubopada";
    "Buboreg";
    "Bubua";
    "Bubumbaret";
    "Bubuweyn";
    "Bubyrydata";
    "Burgbeth";
    "Burgbeth Derry";
    "Burgborne";
    "Burgbrone";
    "Burgbrugh";
    "Burgbury";
    "Burgcart";
    "Burgcart Heath";
    "Burgcastle";
    "Burgcastle Rock";
    "Burgcester";
    "Burgcroft";
    "Burgdale";
    "Burgdale Moor";
    "Burgford";
    "Burgfort";
    "Burggate";
    "Burgham";
    "Burghead";
    "Burghope";
    "Burgidge";
    "Burging";
    "Burglech";
    "Burgleigh";
    "Burgley";
    "Burgmarket Minster";
    "Burgmont";
    "Burgmore";
    "Burgmoth";
    "Burgpath";
    "Burgshire";
    "Burgtale";
    "Burgton";
    "Burgtower Court";
    "Burgtown";
    "Burgtry";
    "Burgtry Commons";
    "Burgvale";
    "Burgvale Moor";
    "Burgville";
    "Burgwall";
    "Burgwall Moor";
    "Burgwark";
    "Burgway";
    "Burgwell";
    "Burgwich";
    "Burgwold";
    "Burgwold Moor";
    "Burgwood";
    "Burgworth";
    "Burgworth End";
    "Burgworth Rock";
    "Burgwych";
    "Buthuton";
    "Byry-Hassi";
    "Cathbeth";
    "Cathbeth Hollow";
    "Cathborne";
    "Cathbridge";
    "Cathbrone";
    "Cathbrone Hall";
    "Cathbrugh";
    "Cathbury";
    "Cathcastle";
    "Cathcester";
    "Cathcroft";
    "Cathdale";
    "Cathford Moor";
    "Cathfort";
    "Cathgare Court";
    "Cathgate";
    "Cathgate Court";
    "Cathham";
    "Cathham Moor";
    "Cathhead";
    "Cathhope";
    "Cathidge";
    "Cathing";
    "Cathlech";
    "Cathleigh";
    "Cathley";
    "Cathmarket";
    "Cathmont";
    "Cathmore";
    "Cathmore Borough";
    "Cathmore Hall";
    "Cathmoth Commons";
    "Cathpath";
    "Cathshire";
    "Cathshire Rock";
    "Cathtale";
    "Cathton";
    "Cathtower Hill";
    "Cathtown";
    "Cathtry";
    "Cathvale";
    "Cathvale Hollow";
    "Cathwark";
    "Cathway";
    "Cathway Derry";
    "Cathwell";
    "Cathwich";
    "Cathwick";
    "Cathwold";
    "Cathwold Hamlet";
    "Cathwold Heath";
    "Cathwood";
    "Cathworth";
    "Cathwych";
    "Cerabi";
    "Ceradbu";
    "Cerajrea";
    "Ceraka-Gora";
    "Ceralla-Korom";
    "Cerallaplex";
    "Cerallawan";
    "Ceranda-Kom";
    "Cerascubi";
    "Cerehzar";
    "Cerekat";
    "Cerelidai";
    "Ceremiweyn";
    "Cerettunia";
    "Ceriburea";
    "Cerilarana";
    "Cerilli-Hassi";
    "Cerjilah";
    "Cerohadata";
    "Ceropator";
    "Cerumbator";
    "Cerunnu-Hassi";
    "Ceryryla";
    "Charbeth";
    "Charborne";
    "Charborne Wood";
    "Charbrone";
    "Charbrugh";
    "Charbury";
    "Charcart";
    "Charcart Rock";
    "Charcastle";
    "Charcester";
    "Charcroft";
    "Charcroft Commons";
    "Chardale";
    "Charenbeth";
    "Charenborne";
    "Charenborne Hollow";
    "Charenbridge";
    "Charenbridge Field";
    "Charenbrone";
    "Charenbrugh";
    "Charenbrugh Hamlet";
    "Charenbury";
    "Charenbury Court";
    "Charencart";
    "Charencastle";
    "Charencester";
    "Charencester Garden";
    "Charencroft";
    "Charendale";
    "Charendale Derry";
    "Charenford";
    "Charenfort";
    "Charengate";
    "Charenham";
    "Charenham End";
    "Charenhead";
    "Charenidge";
    "Charenidge Hollow";
    "Charening";
    "Charening Hill";
    "Charenlech";
    "Charenlech Hall";
    "Charenley";
    "Charenley Derry";
    "Charenmarket";
    "Charenmont";
    "Charenmore";
    "Charenmoth";
    "Charenpath";
    "Charenshire";
    "Charentale";
    "Charenton";
    "Charentower";
    "Charentown";
    "Charentry";
    "Charenvale";
    "Charenvale Hill";
    "Charenville End";
    "Charenwark";
    "Charenwell";
    "Charenwich";
    "Charenwick";
    "Charenwold";
    "Charenwold Hill";
    "Charenwood";
    "Charenworth";
    "Charenwych";
    "Charford";
    "Charfort";
    "Chargate";
    "Charham";
    "Charhead";
    "Charhope";
    "Charidge";
    "Charidge Hall";
    "Charing";
    "Charleigh";
    "Charley";
    "Charley Hollow";
    "Charmarket";
    "Charmont";
    "Charmont Wood";
    "Charmoth";
    "Charshire";
    "Chartale";
    "Charton";
    "Chartower";
    "Chartown";
    "Chartown Rock";
    "Chartry";
    "Charvale";
    "Charville";
    "Charwall";
    "Charwark";
    "Charway";
    "Charway Heath";
    "Charway Rock";
    "Charwell";
    "Charwich";
    "Charwick";
    "Charwold";
    "Charwood";
    "Charwood Garden";
    "Charworth";
    "Charwych";
    "Chesterborne";
    "Chesterbridge";
    "Chesterbrone";
    "Chesterbrone Heath";
    "Chesterbrugh";
    "Chesterbury";
    "Chestercart";
    "Chestercastle";
    "Chestercester";
    "Chestercroft";
    "Chesterdale";
    "Chesterdale Heath";
    "Chesterford";
    "Chesterfort";
    "Chestergate";
    "Chesterham";
    "Chesterhead";
    "Chesterhead Wood";
    "Chesterhope";
    "Chesteridge";
    "Chesteridge End";
    "Chestering";
    "Chesterlech";
    "Chesterleigh";
    "Chesterleigh Hall";
    "Chesterley";
    "Chestermarket";
    "Chestermarket Garden";
    "Chestermont";
    "Chestermore";
    "Chestermoth";
    "Chesterpath";
    "Chestershire";
    "Chestertale";
    "Chesterton";
    "Chestertower";
    "Chestertower Field";
    "Chestertown";
    "Chestertry";
    "Chestervale";
    "Chesterville";
    "Chesterwall";
    "Chesterwall Borough";
    "Chesterwall Garden";
    "Chesterwark";
    "Chesterwark Court";
    "Chesterway";
    "Chesterwell";
    "Chesterwich";
    "Chesterwick";
    "Chesterwick Derry";
    "Chesterwick Hamlet";
    "Chesterwold";
    "Chesterwold Hollow";
    "Chesterwood";
    "Chesterworth";
    "Chesterwych";
    "Crombeth";
    "Crombrone";
    "Crombrugh";
    "Crombury";
    "Crombury Hall";
    "Crombury Moor";
    "Cromcart";
    "Cromcastle";
    "Cromcester";
    "Cromcroft";
    "Cromcroft Borough";
    "Cromdale";
    "Cromford";
    "Cromfort";
    "Cromgate";
    "Cromham";
    "Cromhead";
    "Cromhope";
    "Cromidge";
    "Croming";
    "Cromlech";
    "Cromley";
    "Cromley Wood";
    "Crommarket";
    "Crommont";
    "Crommore";
    "Crommoth";
    "Crommoth Garden";
    "Crompath";
    "Cromshire";
    "Cromtale";
    "Cromton";
    "Cromtower";
    "Cromtown";
    "Cromtown Rock";
    "Cromtry";
    "Cromvale";
    "Cromville Commons";
    "Cromwall";
    "Cromwark";
    "Cromwark Hamlet";
    "Cromway";
    "Cromwell";
    "Cromwich End";
    "Cromwick";
    "Cromwick Hamlet";
    "Cromwold";
    "Cromwood Hall";
    "Cromworth";
    "Cromworth Commons";
    "Cromwych Hill";
    "Crossbeth";
    "Crossborne";
    "Crossbridge";
    "Crossbrone";
    "Crossbrugh";
    "Crossbury";
    "Crosscart";
    "Crosscastle";
    "Crosscester";
    "Crosscroft Derry";
    "Crosscroft Field";
    "Crossdale";
    "Crossdale Moor";
    "Crossford";
    "Crossfort";
    "Crossgate";
    "Crossgate Court";
    "Crossham";
    "Crosshead";
    "Crosshope";
    "Crosshope Court";
    "Crossidge";
    "Crossing";
    "Crosslech";
    "Crossleigh";
    "Crossley";
    "Crossmarket";
    "Crossmont";
    "Crossmore";
    "Crossmoth";
    "Crosspath";
    "Crossshire";
    "Crosstale";
    "Crosstale Wood";
    "Crosston";
    "Crosston Borough";
    "Crosstower";
    "Crosstry";
    "Crossvale";
    "Crossville";
    "Crosswall Commons";
    "Crosswark";
    "Crossway";
    "Crosswell";
    "Crosswich";
    "Crosswick";
    "Crosswold Borough";
    "Crosswood";
    "Crossworth";
    "Crosswych";
    "Crosswych Wood";
    "Cudabu";
    "Cudadkat";
    "Cudahasa";
    "Cudajsia";
    "Cudakasa";
    "Cudalladisu";
    "Cudao";
    "Cudascuara";
    "Cudeh-Hassi";
    "Cudehjet";
    "Cudemi-Korom";
    "Cudena-Hassi";
    "Cudiplex";
    "Cudiridax";
    "Cudirius";
    "Cudjireg";
    "Cudoaweyn";
    "Cudogudax";
    "Cudohaus";
    "Cudoo";
    "Cudotu-Thar";
    "Cuduan";
    "Cudu-Ij";
    "Cudunnuria";
    "Cuduthuplex";
    "Daenia";
    "Daggerfall";
    "Damaaqdisu";
    "Damaaq-Ij";
    "Damalla-Korom";
    "Damandao";
    "Damasta-Korom";
    "Damedisu";
    "Dameho";
    "Damenaweyn";
    "Dameria";
    "Damettu-Thar";
    "Damibuga";
    "Damila-Ij";
    "Daminia";
    "Daminzar";
    "Damiriria";
    "Damissila";
    "Damoa-Hassi";
    "Damocco-Gora";
    "Damohaus";
    "Damohazar";
    "Damonidax";
    "Damu-Ij";
    "Damu-Kom";
    "Damunnutor";
    "Damuthuplex";
    "Deerbeth";
    "Deerborne";
    "Deerbridge";
    "Deerbridge Hollow";
    "Deerbrone";
    "Deerbrugh";
    "Deerbury";
    "Deercart";
    "Deercastle";
    "Deercester";
    "Deercroft";
    "Deercroft Minster";
    "Deerdale";
    "Deerford";
    "Deerfort";
    "Deerham";
    "Deerhead";
    "Deerhope";
    "Deeridge";
    "Deering";
    "Deering Borough";
    "Deerlech";
    "Deerlech Derry";
    "Deerleigh";
    "Deermont";
    "Deermore";
    "Deermoth";
    "Deerpath";
    "Deershire";
    "Deertale";
    "Deerton";
    "Deerton Field";
    "Deertown Field";
    "Deertry";
    "Deervale";
    "Deerville";
    "Deerwall";
    "Deerwark";
    "Deerway";
    "Deerwell";
    "Deerwich";
    "Deerwick";
    "Deerwick Hall";
    "Deerwood";
    "Deerworth";
    "Deerwych";
    "Dragontail";
    "Dwynnen";
    "Eastbeth";
    "Eastborne";
    "Eastborne Heath";
    "Eastbridge";
    "Eastbrone";
    "Eastbury";
    "Eastcart";
    "Eastcastle";
    "Eastcester";
    "Eastcroft";
    "Eastdale";
    "Eastford";
    "Eastfort";
    "Eastfort Rock";
    "Eastgate";
    "Eastgate End";
    "Eastham Hill";
    "Easthead";
    "Eastidge";
    "Eastidge End";
    "Easting";
    "Easting Rock";
    "Eastlech";
    "Eastley";
    "Eastmarket";
    "Eastmont";
    "Eastmore";
    "Eastmoth";
    "Eastpath";
    "Eastshire";
    "Easttale";
    "Eastton";
    "Easttower";
    "Easttower Hollow";
    "Easttown";
    "Easttry";
    "Eastvale";
    "Eastvale Rock";
    "Eastville";
    "Eastville Derry";
    "Eastwall";
    "Eastwark";
    "Eastwell";
    "Eastwell Commons";
    "Eastwich";
    "Eastwick";
    "Eastwick Moor";
    "Eastwold";
    "Eastwood";
    "Eastworth";
    "Elajtor";
    "Elakania";
    "Elania";
    "Elekat";
    "Elelila";
    "Eleraa";
    "Elettubu";
    "Elii-Gora";
    "Elii-Korom";
    "Elilabi";
    "Elila-Ij";
    "Elissinia";
    "Eloator";
    "Eloha-Hassi";
    "Eloni-Korom";
    "Elopaan";
    "Elotunia";
    "Elu-Gora";
    "Eluhkat";
    "Elumbator";
    "Elu-Thar";
    "Eluthubi";
    "Ephesus";
    "Fontbeth";
    "Fontborne";
    "Fontbridge";
    "Fontbrone";
    "Fontbrugh";
    "Fontbury";
    "Fontcart";
    "Fontcastle";
    "Fontcastle Court";
    "Fontcester";
    "Fontcester Rock";
    "Fontcroft";
    "Fontdale";
    "Fontford";
    "Fontfort";
    "Fontgate";
    "Fontgate Hollow";
    "Fontham";
    "Fonthead";
    "Fonthope";
    "Fonthope End";
    "Fonthope Hall";
    "Fonthope Minster";
    "Fontidge";
    "Fonting";
    "Fontlech";
    "Fontleigh";
    "Fontley";
    "Fontmarket";
    "Fontmore";
    "Fontmore Heath";
    "Fontmoth";
    "Fontpath";
    "Fontshire";
    "Fontton";
    "Fonttower";
    "Fonttown";
    "Fonttry";
    "Fontvale";
    "Fontville";
    "Fontwall";
    "Fontway";
    "Fontwell";
    "Fontwell Court";
    "Fontwell Heath";
    "Fontwich";
    "Fontwick";
    "Fontwold";
    "Fontwood";
    "Fontwood Garden";
    "Fontworth";
    "Fontwych";
    "Gallobeth";
    "Galloborne";
    "Gallobrone";
    "Gallobrugh";
    "Gallobury";
    "Gallocart";
    "Gallocastle";
    "Gallocester";
    "Gallodale";
    "Gallodale Minster";
    "Galloford";
    "Galloford Garden";
    "Gallofort";
    "Gallogate";
    "Gallogate Field";
    "Galloham";
    "Galloham End";
    "Gallohope";
    "Gallohope Rock";
    "Galloidge";
    "Galloing";
    "Galloing Garden";
    "Galloing Hamlet";
    "Gallolech Borough";
    "Galloleigh";
    "Galloley";
    "Gallomarket";
    "Gallomont";
    "Gallomont Commons";
    "Gallomore";
    "Gallomoth";
    "Gallopath";
    "Galloshire";
    "Gallotale";
    "Galloton";
    "Gallotower";
    "Gallotown";
    "Gallotry";
    "Gallovale";
    "Gallovale Moor";
    "Galloville";
    "Gallowall";
    "Gallowark";
    "Gallowell";
    "Gallowich";
    "Gallowick";
    "Gallowold";
    "Gallowood";
    "Galloworth";
    "Galloworth Heath";
    "Gallowych";
    "Gavaudon";
    "Glenpoint";
    "Glenumbra";
    "Gothborne";
    "Gothbridge";
    "Gothbrone";
    "Gothbury";
    "Gothcart";
    "Gothcart Hamlet";
    "Gothcastle";
    "Gothcester";
    "Gothcroft";
    "Gothdale";
    "Gothford";
    "Gothfort";
    "Gothgate";
    "Gothham";
    "Gothhead";
    "Gothhope";
    "Gothidge";
    "Gothing";
    "Gothlech";
    "Gothleigh";
    "Gothley";
    "Gothmarket";
    "Gothmont";
    "Gothmoth";
    "Gothpath";
    "Gothshire";
    "Gothtale";
    "Gothton";
    "Gothton End";
    "Gothtower";
    "Gothvale";
    "Gothwall";
    "Gothwark";
    "Gothwark Hollow";
    "Gothwark Rock";
    "Gothway";
    "Gothway Garden";
    "Gothway Hall";
    "Gothwell";
    "Gothwich";
    "Gothwick";
    "Gothwold";
    "Gothwood";
    "Gothworth Commons";
    "Gothwych";
    "Gothwych Heath";
    "Graybeth";
    "Grayborne";
    "Graybridge";
    "Graybrone";
    "Graybrone Court";
    "Graybrugh";
    "Graybury";
    "Graybury Minster";
    "Graycart";
    "Graycastle";
    "Graycester";
    "Graycroft";
    "Graydale";
    "Grayford";
    "Grayfort";
    "Graygate Hollow";
    "Grayham";
    "Grayhead Hall";
    "Grayhope";
    "Grayidge";
    "Graying";
    "Graylech";
    "Grayleigh";
    "Grayley";
    "Graymarket";
    "Graymont";
    "Graymore";
    "Graypath";
    "Grayshire";
    "Graytale";
    "Grayton";
    "Grayton End";
    "Graytower";
    "Graytown";
    "Grayvale";
    "Grayville";
    "Grayville Court";
    "Graywall";
    "Graywark";
    "Grayway";
    "Graywell";
    "Graywich";
    "Graywick";
    "Graywold";
    "Graywold Derry";
    "Graywood";
    "Grayworth";
    "Graywych";
    "Grimbeth";
    "Grimborne";
    "Grimbridge";
    "Grimbridge Wood";
    "Grimbrone";
    "Grimbrugh";
    "Grimbury";
    "Grimbury Derry";
    "Grimcart";
    "Grimcastle";
    "Grimcroft";
    "Grimdale";
    "Grimdale Moor";
    "Grimford";
    "Grimfort";
    "Grimgate";
    "Grimham";
    "Grimhead";
    "Grimhope";
    "Grimidge";
    "Grimidge Garden";
    "Grimidge Minster";
    "Griming";
    "Grimlech Field";
    "Grimleigh";
    "Grimleigh Minster";
    "Grimley";
    "Grimmarket";
    "Grimmore";
    "Grimmoth";
    "Grimpath";
    "Grimshire";
    "Grimtale";
    "Grimtale End";
    "Grimton";
    "Grimtower Hall";
    "Grimtower Hollow";
    "Grimtown";
    "Grimtry";
    "Grimtry Garden";
    "Grimvale";
    "Grimvale Borough";
    "Grimville";
    "Grimwall";
    "Grimwark";
    "Grimway";
    "Grimwell";
    "Grimwich";
    "Grimwich Borough";
    "Grimwick";
    "Grimwood";
    "Grimworth";
    "Grimworth Hall";
    "Grimwych";
    "Gysaha-Gora";
    "Gysaj-Hassi";
    "Gysaka-Ij";
    "Gysator";
    "Gyselah";
    "Gyselibu";
    "Gysera-Thar";
    "Gysiian";
    "Gysilah";
    "Gysila-Korom";
    "Gysillirea";
    "Gysinbi";
    "Gysinla";
    "Gysoccoan";
    "Gysoniplex";
    "Gysosa";
    "Gysotuara";
    "Gysotukat";
    "Gysuhan";
    "Gysumbakat";
    "Gysunia";
    "Gysunnuo";
    "Gysyrybu";
    "Hadus";
    "Handa-Hassi";
    "Haplex";
    "Ha-Thar";
    "Hebu";
    "Hemio";
    "Hera-Ij";
    "He-Thar";
    "Hettubu";
    "Hibusa";
    "Hidax";
    "Hiiplex";
    "Hillia";
    "Hoaria";
    "Hodax";
    "Hogu-Thar";
    "Holbeth";
    "Holbeth Court";
    "Holborne";
    "Holbridge";
    "Holbrone";
    "Holbrone Moor";
    "Holbury";
    "Holcart";
    "Holcastle";
    "Holcester";
    "Holcroft";
    "Holdale";
    "Holford";
    "Holfort";
    "Holgate";
    "Holham";
    "Holhead";
    "Holhead Court";
    "Holhope";
    "Holidge";
    "Holing";
    "Hollech";
    "Holleigh";
    "Holley";
    "Holley Hill";
    "Holmarket";
    "Holmarket Commons";
    "Holmont";
    "Holmont Borough";
    "Holmore Field";
    "Holmoth";
    "Holpath";
    "Holshire";
    "Holshire Rock";
    "Holtale";
    "Holton";
    "Holtower";
    "Holtown";
    "Holtry";
    "Holtry Hollow";
    "Holvale";
    "Holville";
    "Holwall";
    "Holwark";
    "Holway";
    "Holwell";
    "Holwich";
    "Holwick";
    "Holwold";
    "Holwood";
    "Holwood Garden";
    "Holworth";
    "Holwych";
    "Holwych Minster";
    "Honi-Kom";
    "Horborne Wood";
    "Horbridge";
    "Horbrone";
    "Horbrugh";
    "Horbury";
    "Horcart";
    "Horcastle";
    "Horcester";
    "Horcester Hill";
    "Horcroft";
    "Horcroft Heath";
    "Hordale";
    "Horfort";
    "Horgate";
    "Horham";
    "Horhead";
    "Horhope";
    "Horia";
    "Horidge";
    "Horing";
    "Horleigh";
    "Horley";
    "Hormarket";
    "Hormore";
    "Horpath";
    "Horshire";
    "Hortale";
    "Horton";
    "Horton Derry";
    "Horton Hamlet";
    "Hortower";
    "Hortower Derry";
    "Hortown";
    "Hortry";
    "Horvale";
    "Horville";
    "Horwall";
    "Horwark";
    "Horway Hollow";
    "Horwell";
    "Horwick";
    "Horwold";
    "Horwold Field";
    "Horwood Borough";
    "Horworth";
    "Hotunia";
    "Huh-Hassi";
    "Humba-Kom";
    "Huthudisu";
    "Hyryjet";
    "Ilessan Hills";
    "Ipsborne";
    "Ipsbridge";
    "Ipsbrone";
    "Ipsbrugh";
    "Ipsbury";
    "Ipscart";
    "Ipscart Rock";
    "Ipscastle";
    "Ipscroft";
    "Ipsdale";
    "Ipsford";
    "Ipsfort";
    "Ipsgate";
    "Ipsham";
    "Ipshead";
    "Ipsidge";
    "Ipsing";
    "Ipslech";
    "Ipsleigh";
    "Ipsleigh Hill";
    "Ipsley";
    "Ipsmarket";
    "Ipsmont";
    "Ipsmont Heath";
    "Ipsmore";
    "Ipsmoth";
    "Ipspath";
    "Ipsshire";
    "Ipsshire Borough";
    "Ipsshire Hall";
    "Ipstale";
    "Ipstale Hill";
    "Ipston";
    "Ipstower";
    "Ipstown";
    "Ipstry";
    "Ipsvale";
    "Ipsville";
    "Ipswall";
    "Ipswark";
    "Ipswark Hollow";
    "Ipsway";
    "Ipswich";
    "Ipswick";
    "Ipswold";
    "Ipswood";
    "Ipsworth";
    "Ipsworth Field";
    "Isfadreg";
    "Isfahaan";
    "Isfakabi";
    "Isfakat";
    "Isfascuara";
    "Isfastania";
    "Isfeho";
    "Isfe-Korom";
    "Isfemiret";
    "Isfibia";
    "Isfibu-Gora";
    "Isfijer";
    "Isfillisa";
    "Isfinjer";
    "Isfissius";
    "Isfji-Korom";
    "Isfoa";
    "Isfoguara";
    "Isfoharia";
    "Isfopao";
    "Isfunnusa";
    "Isfuthuara";
    "Isfyryus";
    "Issaqaaqreg";
    "Issaqajton";
    "Issaqeara";
    "Issaqeisa";
    "Issaqelikat";
    "Issaqeraga";
    "Issaqettubia";
    "Issaqiia";
    "Issaqiladax";
    "Issaqoa-Kom";
    "Issaqonireg";
    "Issaqoreg";
    "Issaqotubia";
    "Issaqous";
    "Issaquhkat";
    "Issaqujer";
    "Issaqumbaa";
    "Issaqumbaan";
    "Issaqunnujet";
    "Issaquplex";
    "Issaquthuda";
    "Issaqyryisa";
    "Jaladnia";
    "Jalahao";
    "Jalakaplex";
    "Jala-Korom";
    "Jalallaara";
    "Jalaria";
    "Jalascu-Korom";
    "Jale-Gora";
    "Jalehbia";
    "Jalelian";
    "Jalenasia";
    "Jalenis";
    "Jalijer";
    "Jalilajer";
    "Jalilli-Korom";
    "Jaljiara";
    "Jalobu";
    "Jalonia";
    "Jalosa";
    "Jaluh-Thar";
    "Jaluhtor";
    "Jalumba-Hassi";
    "Jalyrykat";
    "Javaaqdax";
    "Javajjet";
    "Javakaplex";
    "Javallanis";
    "Javandasia";
    "Javascudax";
    "Javehria";
    "Javejet";
    "Javeli-Hassi";
    "Javenia";
    "Javettubia";
    "Javibia";
    "Javii-Kom";
    "Javilareg";
    "Javinkat";
    "Javoan";
    "Javoccoton";
    "Javoha-Thar";
    "Javoniplex";
    "Javopaus";
    "Javotubia";
    "Javunnunu";
    "Javyrykat";
    "Javyryria";
    "Kairou";
    "Kalaan";
    "Kaladdax";
    "Kalahanu";
    "Kalallaa";
    "Kalelius";
    "Kalenaret";
    "Kalereg";
    "Kalidax";
    "Kaliisia";
    "Kalio";
    "Kaliridata";
    "Kalirikat";
    "Kaloga";
    "Kaloguja";
    "Kaloninis";
    "Kaloton";
    "Kalotuisa";
    "Kalubia";
    "Kaluhbia";
    "Kalumbaisa";
    "Kalunnunu";
    "Kalureg";
    "Kaluthuara";
    "Kalyryda";
    "Kambria";
    "Karlandaplex";
    "Khajaaqnia";
    "Khajajret";
    "Khajallasa";
    "Khajandaa";
    "Khajastareg";
    "Khajenao";
    "Khajeraara";
    "Khajettujer";
    "Khajeus";
    "Khajiinis";
    "Khajilaara";
    "Khajinria";
    "Khajisa";
    "Khajissiza";
    "Khajjia";
    "Khajoajet";
    "Khajoasa";
    "Khajocconu";
    "Khajogujer";
    "Khajoharet";
    "Khajojer";
    "Khajusia";
    "Kirkbeth";
    "Kirkbeth Hamlet";
    "Kirkborne";
    "Kirkborne Hall";
    "Kirkbridge";
    "Kirkbrone";
    "Kirkbrugh";
    "Kirkbury";
    "Kirkbury Court";
    "Kirkcart";
    "Kirkcart Wood";
    "Kirkcastle";
    "Kirkcester";
    "Kirkcroft";
    "Kirkdale";
    "Kirkfort";
    "Kirkfort Borough";
    "Kirkgate";
    "Kirkham";
    "Kirkhead";
    "Kirkhead Rock";
    "Kirkhope";
    "Kirkidge";
    "Kirking";
    "Kirklech";
    "Kirkleigh";
    "Kirkley";
    "Kirkmarket";
    "Kirkmarket Minster";
    "Kirkmont";
    "Kirkmore";
    "Kirkmoth";
    "Kirkpath";
    "Kirkpath Hamlet";
    "Kirkshire";
    "Kirktale Minster";
    "Kirkton";
    "Kirktower";
    "Kirktown";
    "Kirktry";
    "Kirkvale";
    "Kirkville";
    "Kirkwall";
    "Kirkway";
    "Kirkwell";
    "Kirkwich";
    "Kirkwich Garden";
    "Kirkwick";
    "Kirkwold";
    "Kirkwood";
    "Kirkwood Field";
    "Kirkwood Hollow";
    "Kirkworth";
    "Kirkwych";
    "Knightsbeth";
    "Knightsborne";
    "Knightsbridge";
    "Knightsbrugh";
    "Knightsbury";
    "Knightscart";
    "Knightscastle";
    "Knightscester";
    "Knightscroft";
    "Knightscroft Borough";
    "Knightsdale";
    "Knightsford Borough";
    "Knightsgate";
    "Knightsham";
    "Knightsham Commons";
    "Knightshead";
    "Knightshead Garden";
    "Knightshope";
    "Knightsing";
    "Knightslech";
    "Knightsleigh";
    "Knightsley";
    "Knightsmarket";
    "Knightsmont";
    "Knightsmore";
    "Knightsmoth";
    "Knightspath";
    "Knightspath Hall";
    "Knightsshire";
    "Knightstale";
    "Knightston";
    "Knightstower";
    "Knightstower Hill";
    "Knightstown";
    "Knightstry";
    "Knightstry Hill";
    "Knightsville Heath";
    "Knightswall";
    "Knightswark";
    "Knightsway";
    "Knightsway Field";
    "Knightswell";
    "Knightswich";
    "Knightswick";
    "Knightswold";
    "Knightswood";
    "Knightsworth";
    "Knightswych";
    "Koegria";
    "Kozanset";
    "Lainlyn";
    "Lajrea";
    "Lakaton";
    "Lambeth Minster";
    "Lamborne";
    "Lambridge";
    "Lambrone";
    "Lambrugh";
    "Lambury";
    "Lamcart";
    "Lamcastle";
    "Lamcastle Borough";
    "Lamcastle Hall";
    "Lamcester";
    "Lamcroft";
    "Lamcroft Court";
    "Lamdale";
    "Lamdale Heath";
    "Lamford";
    "Lamford Hamlet";
    "Lamfort";
    "Lamgate";
    "Lamham";
    "Lamhead";
    "Lamidge";
    "Laming";
    "Lamlech";
    "Lamleigh";
    "Lamley";
    "Lamley Derry";
    "Lamley Field";
    "Lammarket";
    "Lammont";
    "Lammont Hall";
    "Lammore";
    "Lammore Commons";
    "Lammoth";
    "Lampath";
    "Lamshire";
    "Lamtale";
    "Lamton";
    "Lamton Hamlet";
    "Lamtower";
    "Lamtown";
    "Lamtry";
    "Lamvale";
    "Lamville Hollow";
    "Lamwall";
    "Lamwark";
    "Lamway";
    "Lamwell";
    "Lamwich";
    "Lamwick";
    "Lamwold";
    "Lamwood";
    "Lamwood Moor";
    "Lamworth";
    "Lamwych";
    "Lamwych Hall";
    "Lastabia";
    "Lelidai";
    "Lemisia";
    "Lenada";
    "Lerawan";
    "Leza";
    "Lezar";
    "Liga";
    "Lijer";
    "Lilalah";
    "Linisa";
    "Linno";
    "Loaga";
    "Locconis";
    "Lodai";
    "Logurana";
    "Longbeth";
    "Longborne";
    "Longbridge";
    "Longbrone";
    "Longbrugh";
    "Longbrugh Moor";
    "Longbury";
    "Longbury Hollow";
    "Longcart";
    "Longcastle";
    "Longcastle Borough";
    "Longcastle Minster";
    "Longcester";
    "Longcroft";
    "Longdale";
    "Longford";
    "Longfort";
    "Longgate";
    "Longham";
    "Longham Garden";
    "Longhead";
    "Longhead End";
    "Longhope";
    "Longhope End";
    "Longhope Garden";
    "Longidge";
    "Longidge Moor";
    "Longing";
    "Longlech";
    "Longleigh";
    "Longleigh End";
    "Longley";
    "Longley Borough";
    "Longmarket";
    "Longmarket Garden";
    "Longmont";
    "Longmore";
    "Longmore Field";
    "Longmoth";
    "Longmoth Moor";
    "Longpath";
    "Longshire";
    "Longtale";
    "Longtale Heights";
    "Longton";
    "Longtower";
    "Longtown";
    "Longtry";
    "Longtry Field";
    "Longvale";
    "Longville";
    "Longwall";
    "Longwark";
    "Longwark Rock";
    "Longway";
    "Longway Minster";
    "Longwell";
    "Longwell Hill";
    "Longwich";
    "Longwich Commons";
    "Longwich End";
    "Longwold";
    "Longwold Court";
    "Longwold Minster";
    "Longwood";
    "Longworth";
    "Longwych";
    "Longwych Commons";
    "Longwych Garden";
    "Lopadai";
    "Luwan";
    "Lyryno";
    "Maaqrana";
    "Madla";
    "Makadrana";
    "Makaja";
    "Makaj-Gora";
    "Makajria";
    "Makaka-Ij";
    "Makascubi";
    "Makawan";
    "Makehda";
    "Makeliria";
    "Makemiga";
    "Makiburea";
    "Makila-Thar";
    "Makilliweyn";
    "Makoada";
    "Makodisu";
    "Makohala";
    "Makonilah";
    "Makopator";
    "Makorana";
    "Makowan";
    "Makuhdata";
    "Makumbazar";
    "Makyryla";
    "Malla-Korom";
    "Manda-Gora";
    "Mastaja";
    "Meli-Hassi";
    "Memi-Hassi";
    "Menakat";
    "Menevia";
    "Merbeth";
    "Merbridge";
    "Merbrone";
    "Merbrone Field";
    "Merbrugh";
    "Merbury";
    "Mercastle";
    "Mercastle Garden";
    "Mercester";
    "Mercroft Court";
    "Merdale";
    "Merford";
    "Merfort";
    "Mergate";
    "Merham";
    "Merham Heath";
    "Merhead";
    "Merhope";
    "Merhope Hall";
    "Meridge";
    "Mering";
    "Merlech";
    "Merleigh";
    "Merley";
    "Mermarket";
    "Mermont";
    "Mermont Minster";
    "Mermore";
    "Mermoth";
    "Mermoth Hill";
    "Merpath";
    "Mershire";
    "Mertale";
    "Mertale Court";
    "Merton";
    "Mertower";
    "Mertown";
    "Mertry";
    "Mervale";
    "Merville";
    "Merwall";
    "Merwark Hollow";
    "Merway";
    "Merwich Hill";
    "Merwick";
    "Merwold";
    "Merwood";
    "Merworth";
    "Merwych";
    "Mesadno";
    "Mesajer";
    "Mesanis";
    "Mesascuza";
    "Mesehret";
    "Mesekat";
    "Meseminu";
    "Meseraara";
    "Mesettuara";
    "Mesettudax";
    "Mesiijet";
    "Mesillinis";
    "Mesirija";
    "Mesiton";
    "Mesolah";
    "Mesoniara";
    "Mesonisia";
    "Mesopada";
    "Mesotuus";
    "Mesuhjet";
    "Mesumbasia";
    "Mesureg";
    "Mesuthusa";
    "Mesyrydai";
    "Metor";
    "Mettula";
    "Mibu";
    "Mibu-Kom";
    "Midbeth";
    "Midborne";
    "Midbridge";
    "Midbrone";
    "Midbrugh";
    "Midbrugh Hollow";
    "Midbury";
    "Midcart";
    "Midcastle Borough";
    "Midcester";
    "Midcroft";
    "Midford";
    "Midfort";
    "Midfort Derry";
    "Midgate";
    "Midham";
    "Midhead";
    "Midhope";
    "Mididge";
    "Miding";
    "Midlech";
    "Midleigh";
    "Midley";
    "Midley Moor";
    "Midmarket";
    "Midmarket Rock";
    "Midmont";
    "Midmore";
    "Midmoth";
    "Midpath";
    "Midpath Hill";
    "Midshire";
    "Midtale";
    "Midtown";
    "Midtry";
    "Midvale";
    "Midville";
    "Midwall";
    "Midwall Borough";
    "Midwark";
    "Midwark Field";
    "Midway";
    "Midwell";
    "Midwich";
    "Midwick";
    "Midwold";
    "Midworth";
    "Midwych";
    "Mi-Korom";
    "Millitor";
    "Minzar";
    "Missibi";
    "Mji-Ij";
    "Mji-Kom";
    "Moa-Gora";
    "Moccolah";
    "Mogadax";
    "Mogadbia";
    "Mogahanu";
    "Mogakaa";
    "Mogakareg";
    "Mogallaja";
    "Mogandaton";
    "Mogaret";
    "Mogascubia";
    "Mogascureg";
    "Mogastabia";
    "Mogeja";
    "Mogenazar";
    "Mogiga";
    "Mogiida";
    "Mogiisa";
    "Mogindai";
    "Mogirijer";
    "Mogoccorea";
    "Mogohadata";
    "Mogoniga";
    "Mogopaa";
    "Mogubi";
    "Mogudata";
    "Mogyryzar";
    "Mohania";
    "Moraaqza";
    "Moradza";
    "Morahada";
    "Moraisa";
    "Morakaton";
    "Morandaga";
    "Morascubia";
    "Morastadata";
    "Morastaja";
    "Morehdata";
    "Moremizar";
    "Morenanu";
    "Moribua";
    "Moridata";
    "Morilliton";
    "Morirana";
    "Moriribia";
    "Morissibia";
    "Morjireg";
    "Moroccoa";
    "Morohaan";
    "Moropanu";
    "Moruton";
    "Mournoth";
    "Moweyn";
    "Myrkwasa";
    "Naraharet";
    "Narakaton";
    "Naranu";
    "Narehdai";
    "Narelidai";
    "Naremida";
    "Narenajer";
    "Nareranis";
    "Naresa";
    "Naribuga";
    "Narillisa";
    "Narinus";
    "Naririret";
    "Narjija";
    "Narjiza";
    "Naroajet";
    "Narogujer";
    "Narogunis";
    "Narohano";
    "Naronu";
    "Naroza";
    "Naruara";
    "Narusia";
    "Newbeth";
    "Newbeth Commons";
    "Newborne";
    "Newborne Hollow";
    "Newbridge Field";
    "Newbrone";
    "Newbrugh";
    "Newbury";
    "Newcart";
    "Newcastle";
    "Newcester";
    "Newcroft";
    "Newdale";
    "Newford";
    "Newford Wood";
    "Newfort";
    "Newfort End";
    "Newham";
    "Newhead";
    "Newhope";
    "Newhope Field";
    "Newidge";
    "Newing";
    "Newlech";
    "Newlech Field";
    "Newleigh";
    "Newley";
    "Newmarket";
    "Newmont";
    "Newmore";
    "Newmore Hollow";
    "Newmoth";
    "Newpath";
    "Newshire";
    "Newtale";
    "Newtower";
    "Newtown";
    "Newtown Hollow";
    "Newtry";
    "Newvale";
    "Newville";
    "Newville Court";
    "Newwall";
    "Newwark";
    "Newway";
    "Newwell";
    "Newwick";
    "Newwold";
    "Newwood";
    "Newwood Wood";
    "Newworth";
    "Newwych";
    "Northmoor";
    "Orsinium";
    "Osaaqton";
    "Osabi";
    "Osajdai";
    "Osallaja";
    "Osandarea";
    "Osareg";
    "Osascuton";
    "Osedata";
    "Oselah";
    "Osenabu";
    "Osettuja";
    "Osilawan";
    "Osillida";
    "Osillinu";
    "Osissibia";
    "Osoazar";
    "Oso-Ij";
    "Osopaisa";
    "Osoturet";
    "Osubi";
    "Osuhla";
    "Osumbaweyn";
    "Osunnunu";
    "Osuza";
    "Oxbeth";
    "Oxborne";
    "Oxbridge";
    "Oxbrone";
    "Oxbrugh";
    "Oxbury";
    "Oxbury Rock";
    "Oxcart";
    "Oxcastle";
    "Oxcester";
    "Oxcroft";
    "Oxdale Derry";
    "Oxford";
    "Oxfort";
    "Oxgate";
    "Oxham";
    "Oxham Field";
    "Oxhead";
    "Oxhope";
    "Oxidge";
    "Oxlech";
    "Oxleigh";
    "Oxley";
    "Oxmarket";
    "Oxmont";
    "Oxmoth";
    "Oxpath End";
    "Oxshire";
    "Oxshire Hill";
    "Oxtale";
    "Oxton";
    "Oxtower";
    "Oxtown";
    "Oxtry";
    "Oxtry Borough";
    "Oxvale";
    "Oxvale Borough";
    "Oxville";
    "Oxwall";
    "Oxwark";
    "Oxway";
    "Oxwell";
    "Oxwich";
    "Oxwick";
    "Oxwold";
    "Oxwood";
    "Oxworth";
    "Oxworth Hamlet";
    "Oxworth Hill";
    "Oxwych";
    "Paaqlah";
    "Paja";
    "Pajda";
    "Pallaton";
    "Pandanis";
    "Papabi";
    "Papadata";
    "Papadbu";
    "Papahalah";
    "Papakalah";
    "Papascubi";
    "Papehzar";
    "Papibu";
    "Papibu-Korom";
    "Papiidai";
    "Papiiton";
    "Papiladisu";
    "Papohadata";
    "Papo-Ij";
    "Paponija";
    "Paponirea";
    "Papoparea";
    "Papotuno";
    "Papuhdai";
    "Papumba-Hassi";
    "Papuza";
    "Papyrydai";
    "Peliisa";
    "Penazar";
    "Penbeth";
    "Penbridge";
    "Penbrone";
    "Penbrugh";
    "Penbury";
    "Penbury Garden";
    "Penbury Hamlet";
    "Pencart";
    "Pencester";
    "Pencroft";
    "Pendale";
    "Penford";
    "Penfort";
    "Penfort Derry";
    "Pengate";
    "Pengate Derry";
    "Penham";
    "Penhead Minster";
    "Penhope";
    "Penhope Garden";
    "Penidge";
    "Pening";
    "Pening Minster";
    "Penlech";
    "Penley";
    "Penmarket";
    "Penmore";
    "Penmoth";
    "Peno";
    "Penpath";
    "Penpath Derry";
    "Penshire";
    "Pentale";
    "Pentale Commons";
    "Penton";
    "Pentower";
    "Pentower Moor";
    "Pentown";
    "Pentry";
    "Penu";
    "Penvale";
    "Penville";
    "Penville Moor";
    "Penwall";
    "Penwall Derry";
    "Penwark";
    "Penwell";
    "Penwich";
    "Penwick";
    "Penwick Wood";
    "Penwold";
    "Penwood";
    "Penworth";
    "Penworth Hill";
    "Penwych";
    "Peraja";
    "Pheonadla";
    "Pheonahator";
    "Pheonahaweyn";
    "Pheonandada";
    "Pheonastanis";
    "Pheonazar";
    "Pheonega";
    "Pheoneradisu";
    "Pheonettuza";
    "Pheonewan";
    "Pheonirila";
    "Pheoniritor";
    "Pheoniza";
    "Pheonoccoga";
    "Pheonogu-Ij";
    "Pheonolah";
    "Pheono-Thar";
    "Pheonotuwan";
    "Pheonuhno";
    "Pheonumbadai";
    "Pheonunnurea";
    "Pheonurana";
    "Pheonuthuweyn";
    "Pheonutor";
    "Phrygias";
    "Pibuda";
    "Pilaja";
    "Pilliweyn";
    "Pinret";
    "Pireg";
    "Pissibi";
    "Pjiga";
    "Poadai";
    "Podata";
    "Pothago";
    "Pumbarea";
    "Punnuzar";
    "Puthuton";
    "Puweyn";
    "Pythadbia";
    "Pythadjer";
    "Pythahajet";
    "Pythajdai";
    "Pythakanis";
    "Pythallaga";
    "Pythandarea";
    "Pythedai";
    "Pythelida";
    "Pythettuno";
    "Pythiisa";
    "Pythilaza";
    "Pythinis";
    "Pythoccowan";
    "Pythohajer";
    "Pythonilah";
    "Pythosia";
    "Pythotula";
    "Pythoturana";
    "Pythunnuweyn";
    "Pythuwan";
    "Pythyrisa";
    "Pythyryret";
    "Ramaaqwan";
    "Rama-Ij";
    "Ramakawan";
    "Ramala";
    "Ramallabi";
    "Ramasta-Korom";
    "Rameh-Thar";
    "Ramehtor";
    "Ramemi-Gora";
    "Ramemitor";
    "Rameralah";
    "Ramibuga";
    "Ramillio";
    "Raminzar";
    "Ramirirana";
    "Ramissi-Thar";
    "Ramji-Ij";
    "Ramoaweyn";
    "Ramoga";
    "Ramoguwan";
    "Ramohabu";
    "Ramohada";
    "Ramonidisu";
    "Ramoparia";
    "Ramyryzar";
    "Reybeth";
    "Reyborne";
    "Reybridge";
    "Reybridge Moor";
    "Reybrone";
    "Reybrugh Minster";
    "Reybury";
    "Reycart";
    "Reycastle";
    "Reycester";
    "Reycroft";
    "Reydale";
    "Reyford";
    "Reyford Moor";
    "Reyfort";
    "Reygate";
    "Reyham";
    "Reyham End";
    "Reyhead";
    "Reyhope";
    "Reyidge Garden";
    "Reying";
    "Reyleigh";
    "Reyley";
    "Reymarket";
    "Reymont";
    "Reymoth";
    "Reypath";
    "Reypath Rock";
    "Reyshire";
    "Reyshire Derry";
    "Reyshire Minster";
    "Reytale";
    "Reytale Field";
    "Reyton";
    "Reytower";
    "Reytown";
    "Reytry";
    "Reyvale";
    "Reyville";
    "Reywark";
    "Reyway";
    "Reyway Derry";
    "Reywell";
    "Reywich";
    "Reywick";
    "Reywold";
    "Reywold Hollow";
    "Reyworth";
    "Reywych";
    "Rhanajo";
    "Rhanaka-Korom";
    "Rhanandasa";
    "Rhanano";
    "Rhanascuja";
    "Rhanastaara";
    "Rhaneliria";
    "Rhaneraza";
    "Rhanereg";
    "Rhanibuo";
    "Rhaninjer";
    "Rhaniriza";
    "Rhanissiara";
    "Rhanjisa";
    "Rhanoccoara";
    "Rhanoccosia";
    "Rhanopa-Hassi";
    "Rhanotujer";
    "Rhanuhret";
    "Rhanumbanu";
    "Rhanunnusia";
    "Rhanuthunis";
    "Rhanyrybia";
    "Rhogaaq-Korom";
    "Rhogaddata";
    "Rhogadrana";
    "Rhogahadai";
    "Rhogaj-Hassi";
    "Rhogallalah";
    "Rhogandarea";
    "Rhogascuplex";
    "Rhogastabu";
    "Rhogelibu";
    "Rhogenaria";
    "Rhogila";
    "Rhogilah";
    "Rhogilli-Kom";
    "Rhogillirea";
    "Rhogissinia";
    "Rhogjibi";
    "Rhogocco-Korom";
    "Rhogorea";
    "Rhogotu-Hassi";
    "Rhogubu";
    "Rhogunnu-Gora";
    "Rhogunnu-Kom";
    "Rhogusa";
    "Ripbeth";
    "Ripborne";
    "Ripbridge";
    "Ripbrone";
    "Ripbrone Commons";
    "Ripbrugh";
    "Ripbury";
    "Ripcart Moor";
    "Ripcastle";
    "Ripcastle Wood";
    "Ripcester";
    "Ripcester Rock";
    "Ripcester Wood";
    "Ripcroft";
    "Ripcroft Hall";
    "Ripdale";
    "Ripford";
    "Ripfort";
    "Ripgate";
    "Ripgate Field";
    "Ripham";
    "Riphead";
    "Riphope";
    "Ripidge";
    "Riping";
    "Riplech";
    "Ripleigh";
    "Ripley";
    "Ripmarket";
    "Ripmont";
    "Ripmont Court";
    "Ripmore";
    "Ripmoth";
    "Rippath";
    "Rippath Heath";
    "Ripshire";
    "Ripshire Heath";
    "Riptale";
    "Ripton";
    "Riptower";
    "Riptown";
    "Riptry";
    "Ripvale";
    "Ripville";
    "Ripwall";
    "Ripwark";
    "Ripway";
    "Ripwell";
    "Ripwich";
    "Ripwick";
    "Ripwick Garden";
    "Ripwold";
    "Ripwold End";
    "Ripwood";
    "Ripwych";
    "Ripwych Commons";
    "Ripwych Heath";
    "Santaki";
    "Satakalaam";
    "Sedaara";
    "Sedaha-Kom";
    "Sedajus";
    "Sedakat";
    "Sedastalah";
    "Sede-Korom";
    "Sedemian";
    "Sedena-Hassi";
    "Sedera-Korom";
    "Sederania";
    "Sederia";
    "Sedettu-Thar";
    "Sedinbu";
    "Sedissibi";
    "Sedoakat";
    "Sedocco-Gora";
    "Sedogukat";
    "Sedogunia";
    "Sedojer";
    "Sedoplex";
    "Sedu-Ij";
    "Sedunnutor";
    "Seduthuo";
    "Sentinel";
    "Shalgora";
    "Singbeth";
    "Singborne";
    "Singborne Court";
    "Singbridge";
    "Singbrone";
    "Singbrugh";
    "Singbrugh Commons";
    "Singbrugh Wood";
    "Singbury";
    "Singcart";
    "Singcastle";
    "Singcester";
    "Singcester Court";
    "Singcroft";
    "Singdale";
    "Singford";
    "Singfort";
    "Singgate";
    "Singham";
    "Singham Hall";
    "Singhead";
    "Singhead Minster";
    "Singhope";
    "Singidge Derry";
    "Singing";
    "Singlech";
    "Singleigh";
    "Singley";
    "Singmarket";
    "Singmont";
    "Singmore";
    "Singmoth";
    "Singpath";
    "Singshire";
    "Singshire Rock";
    "Singtale";
    "Sington";
    "Singtower";
    "Singtower Commons";
    "Singtower Hamlet";
    "Singtown";
    "Singtry";
    "Singvale";
    "Singwall";
    "Singwark";
    "Singway";
    "Singwell";
    "Singwich";
    "Singwick";
    "Singwold";
    "Singwood";
    "Singworth";
    "Singwych";
    "Stokbeth";
    "Stokbridge";
    "Stokbrone";
    "Stokbrugh";
    "Stokcart Garden";
    "Stokcastle";
    "Stokcroft";
    "Stokdale";
    "Stokford";
    "Stokford End";
    "Stokfort";
    "Stokham";
    "Stokhead";
    "Stokhead Hollow";
    "Stokidge";
    "Stoking";
    "Stoklech";
    "Stokleigh";
    "Stokley";
    "Stokmarket";
    "Stokmarket Commons";
    "Stokmore";
    "Stokmoth";
    "Stokmoth Hollow";
    "Stokpath";
    "Stokshire";
    "Stoktale";
    "Stokton";
    "Stoktower";
    "Stoktown";
    "Stoktry";
    "Stokvale";
    "Stokville";
    "Stokwall";
    "Stokwark";
    "Stokway";
    "Stokwell Derry";
    "Stokwick";
    "Stokwold";
    "Stokwood";
    "Stokworth";
    "Stokworth Minster";
    "Stokworth Moor";
    "Stokwych";
    "Stokwych Field";
    "Stokwych Hamlet";
    "Syrajplex";
    "Syrakaplex";
    "Syra-Kom";
    "Syrallao";
    "Syrasa";
    "Syrascu-Thar";
    "Syremia";
    "Syriidisu";
    "Syrillitor";
    "Syriri-Hassi";
    "Syrissibia";
    "Syrius";
    "Syroara";
    "Syroccoreg";
    "Syrogubu";
    "Syro-Kom";
    "Syroni-Ij";
    "Syrotubu";
    "Syrotula";
    "Syruhus";
    "Syrumbajet";
    "Syrunnuweyn";
    "Syruria";
    "Tambeth";
    "Tamborne";
    "Tambridge";
    "Tambridge Moor";
    "Tambrone";
    "Tambrugh";
    "Tambury";
    "Tambury Hollow";
    "Tamcart";
    "Tamcester";
    "Tamcroft";
    "Tamdale";
    "Tamford";
    "Tamfort";
    "Tamfort Garden";
    "Tamgate";
    "Tamgate End";
    "Tamham";
    "Tamhead";
    "Tamhope";
    "Tamidge";
    "Taming";
    "Tamlech";
    "Tamleigh";
    "Tamley Commons";
    "Tammarket";
    "Tammont";
    "Tammore";
    "Tammoth";
    "Tampath";
    "Tamshire";
    "Tamtale";
    "Tamtale Moor";
    "Tamton";
    "Tamtower";
    "Tamtown";
    "Tamtry";
    "Tamvale";
    "Tamvale Rock";
    "Tamville";
    "Tamwall";
    "Tamwall Wood";
    "Tamwark";
    "Tamwark Heath";
    "Tamway";
    "Tamway Field";
    "Tamway Moor";
    "Tamwell";
    "Tamwich";
    "Tamwich Court";
    "Tamwick";
    "Tamwold";
    "Tamwood";
    "Tamwych";
    "Tasaaqara";
    "Tasalladax";
    "Tasandaplex";
    "Tasastadax";
    "Tasehan";
    "Tasehkat";
    "Tasibusa";
    "Tasiio";
    "Tasillia";
    "Tasiria";
    "Tasirinia";
    "Tasissijer";
    "Tasjiplex";
    "Tasoator";
    "Tasogu-Korom";
    "Tasohakat";
    "Tasohania";
    "Taso-Ij";
    "Tasonisa";
    "Tasoparet";
    "Tasu-Gora";
    "Tasuthu-Kom";
    "Tasyryjer";
    "The Citadel of Shalden";
    "The Dancing Gnome Pub";
    "The Dancing Rascal Tavern";
    "The Dead Djinn Pub";
    "The Devil's Helm Pub";
    "The Dirty Dungeon Hostel";
    "The Feather and Dog Tavern";
    "The Flying Wolf Lodge";
    "The Hold of Wickham";
    "The Knave and Dragon Inn";
    "The Lucky Fairy Pub";
    "The Lynx and Dragon Tavern";
    "The Mole and Skull Inn";
    "The Mole And Sword Inn";
    "The Rat And Barbarian Inn";
    "The Rusty Fawn Lodge";
    "The Rusty Hedgehog Inn";
    "The Savage Mug Lodge";
    "The Savage Stag Hostel";
    "The Silver Hedgehog Pub";
    "The Silver Porcupine Tavern";
    "The Stronghold of Kington";
    "The Tower of Woodsmith";
    "The Unfortunate Giffin Pub";
    "The White Goat Lodge";
    "The White Huntsman Hostel";
    "The White Sword Hostel";
    "Tigonus";
    "Totambu";
    "Tower Yeoming";
    "Tsetadara";
    "Tseta-Korom";
    "Tsetallanis";
    "Tsetandasia";
    "Tsetasta-Thar";
    "Tsetejer";
    "Tsetemikat";
    "Tsetenis";
    "Tsetettubia";
    "Tsetetturia";
    "Tsetilaza";
    "Tsetillian";
    "Tsetinkat";
    "Tsetisa";
    "Tsetissiara";
    "Tsetoaret";
    "Tsetoccosa";
    "Tsetonia";
    "Tsetono";
    "Tsetotuus";
    "Tsetudax";
    "Tsetuhjet";
    "Tsetumbano";
    "Tsetunnuplex";
    "Tsetunu";
    "Tulaaaqreg";
    "Tulaad-Thar";
    "Tulaaha-Hassi";
    "Tulaajsia";
    "Tulaakasia";
    "Tulaascunis";
    "Tulaastania";
    "Tulaedax";
    "Tulaeh-Hassi";
    "Tulaelius";
    "Tulaemi-Kom";
    "Tulaenaan";
    "Tulaenajet";
    "Tulaia";
    "Tulaibuplex";
    "Tulaidax";
    "Tulaillisia";
    "Tulairiisa";
    "Tulajidax";
    "Tulaoanu";
    "Tulaogubia";
    "Tulaopajet";
    "Tulaunnua";
    "Tulaureg";
    "Tulauus";
    "Tulune";
    "Tunbeth";
    "Tunbeth Hamlet";
    "Tunborne";
    "Tunbridge";
    "Tunbrugh";
    "Tunbury";
    "Tuncart";
    "Tuncester";
    "Tuncroft";
    "Tundale";
    "Tunford";
    "Tunford Wood";
    "Tunfort";
    "Tungate";
    "Tunham";
    "Tunhead";
    "Tunhope";
    "Tunidge";
    "Tuning";
    "Tunlech";
    "Tunleigh";
    "Tunley";
    "Tunley Heath";
    "Tunmarket";
    "Tunmont";
    "Tunmore";
    "Tunmoth";
    "Tunpath";
    "Tunshire";
    "Tuntale";
    "Tunton";
    "Tuntower";
    "Tuntown";
    "Tuntown Garden";
    "Tuntry";
    "Tuntry End";
    "Tunvale";
    "Tunwall";
    "Tunwall Borough";
    "Tunway";
    "Tunwell";
    "Tunwell Hollow";
    "Tunwich";
    "Tunwick";
    "Tunwood";
    "Tunwood Heath";
    "Tunworth";
    "Tunwych";
    "Umbaaqwan";
    "Umbajweyn";
    "Umballa-Gora";
    "Umbandadisu";
    "Umbasta-Ij";
    "Umbaus";
    "Umbazar";
    "Umbelibu";
    "Umbenaria";
    "Umbeplex";
    "Umberadax";
    "Umbe-Thar";
    "Umbiladisu";
    "Umbindax";
    "Umbissirana";
    "Umbi-Thar";
    "Umbocco-Kom";
    "Umboccoplex";
    "Umbopala";
    "Umbuhria";
    "Umbumbao";
    "Umbunia";
    "Umbunnuweyn";
    "Upbeth Rock";
    "Upborne";
    "Upbridge";
    "Upbrone";
    "Upbrugh";
    "Upbury";
    "Upcart";
    "Upcastle";
    "Upcester";
    "Upcroft";
    "Updale";
    "Updale Derry";
    "Upford";
    "Upfort";
    "Upgate";
    "Upham";
    "Uphead";
    "Uphead Hill";
    "Uphead Moor";
    "Uphope";
    "Upidge";
    "Uping";
    "Uplech";
    "Uplech Heath";
    "Upleigh";
    "Upmarket";
    "Upmont";
    "Upmore";
    "Uppath";
    "Upshire";
    "Uptale";
    "Uptale End";
    "Upton";
    "Uptower";
    "Uptower Moor";
    "Uptown";
    "Uptry";
    "Uptry Court";
    "Uptry Hamlet";
    "Upvale";
    "Upvale Borough";
    "Upville";
    "Upwall";
    "Upwall Court";
    "Upwark";
    "Upwark Commons";
    "Upway";
    "Upwell";
    "Upwich";
    "Upwick";
    "Upwick End";
    "Upwold";
    "Upwood";
    "Upworth";
    "Upwych";
    "Urvaius";
    "Vanbeth";
    "Vanborne";
    "Vanbridge";
    "Vanbrone";
    "Vanbrugh";
    "Vanbrugh Minster";
    "Vanbury";
    "Vancart Commons";
    "Vancastle";
    "Vancastle Garden";
    "Vancester";
    "Vancroft Hall";
    "Vancroft Wood";
    "Vandale";
    "Vanford";
    "Vanfort";
    "Vanfort Commons";
    "Vangate";
    "Vanham";
    "Vanham Wood";
    "Vanhead";
    "Vanhope Hall";
    "Vanhope Wood";
    "Vanidge End";
    "Vaning";
    "Vanlech";
    "Vanlech Court";
    "Vanley";
    "Vanmarket";
    "Vanmont";
    "Vanmore";
    "Vanmoth";
    "Vanpath";
    "Vanshire";
    "Vantale";
    "Vanton";
    "Vantower";
    "Vantower Court";
    "Vantown";
    "Vantry";
    "Vanvale";
    "Vanvale Hamlet";
    "Vanville";
    "Vanwall Hill";
    "Vanwark";
    "Vanway";
    "Vanwell";
    "Vanwich";
    "Vanwick";
    "Vanwold";
    "Vanwood";
    "Vanwood Hollow";
    "Vanworth";
    "Vanwych";
    "Vellen's Hold";
    "Wadijaaqplex";
    "Wadijabia";
    "Wadijahasia";
    "Wadijajet";
    "Wadijehnu";
    "Wadijeliza";
    "Wadijemida";
    "Wadijerabia";
    "Wadijerareg";
    "Wadijeret";
    "Wadijettujer";
    "Wadijilanis";
    "Wadijinus";
    "Wadijirius";
    "Wadijissidax";
    "Wadijoccoa";
    "Wadijoisa";
    "Wadijoniton";
    "Wadijuan";
    "Wadijunnuan";
    "Wadijuthua";
    "Wadijuthureg";
    "Warbeth";
    "Warborne";
    "Warbridge";
    "Warbridge Hill";
    "Warbrone";
    "Warbrugh";
    "Warbury";
    "Warbury Commons";
    "Warcart";
    "Warcart Hamlet";
    "Warcastle";
    "Warcester";
    "Warcroft";
    "Wardale";
    "Wardale Wood";
    "Warford";
    "Warfort";
    "Wargate";
    "Warham";
    "Warhead";
    "Warhead Borough";
    "Warhope";
    "Waridge";
    "Waridge Hamlet";
    "Waridge Moor";
    "Waring";
    "Warlech";
    "Warlech Minster";
    "Warleigh";
    "Warley";
    "Warmarket";
    "Warmont";
    "Warshire";
    "Wartale";
    "Warton";
    "Wartower";
    "Wartown";
    "Wartry";
    "Wartry Moor";
    "Wartry Wood";
    "Warvale";
    "Warville";
    "Warville Hall";
    "Warwall";
    "Warwark";
    "Warway";
    "Warwell";
    "Warwich";
    "Warwold";
    "Warwood";
    "Warwood Moor";
    "Warworth";
    "Warwych";
    "Wayrest";
    "Westbeth";
    "Westborne";
    "Westbridge";
    "Westbrone";
    "Westbrugh";
    "Westbury"
  ]

let best_match (dist: string -> string -> int) dict word =
  dict |>
    List.map (fun w -> w, dist word w) |>
    List.sort (fun (wa, da) (wb, db) ->
        let c = Pervasives.compare da db in
        if c <> 0 then c else Pervasives.compare wa wb)

let distance_cut margin =
  function
  | [] -> []
  | ((_, min_d) :: _) as list ->
     let threshold = min_d + margin in
     List.filter (fun (w, d) -> d <= threshold) list

let daggerfall_towns = List.map String.lowercase_ascii daggerfall_towns

let count_words s start stop =
  let string_fold f acc start stop s =
    let result = ref acc in
    for i = start to stop - 1 do
      result := f !result s.[i]
    done;
    !result in
  string_fold (fun acc -> function ' ' | '-' -> acc + 1 | _ -> acc) 0 start stop s
                     
let l = levenshtein2
          (* inserting/deleting separators is cheap *)
          (function ' ' | '-' -> 3 |  _ -> 10)
          (function ' ' | '-' -> 3 |  _ -> 10)
          (* correcting separators is cheap, 
             replacing separators is expensive *)
          (fun c1 c2 ->
            match c1, c2 with
            | ' ', '-' | '-', ' ' -> 2
            | ' ', _ | '-', _ | _, ' ' | _, '-' -> 20
            | _ -> 15)
          (fun s length ->
            let l = String.length s in
            (* exact prefix is very good *)
            if l = length then 0
            else match s.[l - length - 1] with
                 | ' ' | '-' -> (* start of word is second best *)
                    count_words s 0 length
                 | _ -> (* otherwise small cost for longer prefixes *)
                    String.length s)
          (fun s i ->
            (* exact suffix is very good *)
            if String.length s = i then 0
            else match s.[i] with
                 | ' ' | '-' -> (* end of word is second best *)
                    count_words s i (String.length s)
                 | _ -> (* otherwise small cost for longer suffixes *)
                    String.length s - i)

let _ =
  best_match l daggerfall_towns "bolton" |> distance_cut 20
          
